#!/usr/bin/env python
# -*- coding:UTF-8 -*-
# XRLAM("Game.Fight.Operate")
#===============================================================================
# 操作码
#===============================================================================
MainUnit = 1				#主将【直接出来】(操作码,key,位置,角色ID,角色名,等级,性别,职业,品阶,HP,MaxHP,Moral,MaxMoral,操作角色ID,技能列表,Buff列表,坐骑ID,坐骑属性,援助列表,援助属性, 翅膀ID, 宠物类型)
HeroUnit = 2				#英雄【直接出来】(操作码,key,位置,角色ID,英雄类型,等级,HP,最大HP,Buff列表, 宠物类型)
MonsterUnit = 3				#怪物【直接出来】(操作码,key,位置,怪物id,等级,HP,MaxHP,Buff列表)
CreateMainUnit = 4			#创建主将【跑步入场】(操作码,key,位置,角色ID,角色名,等级,性别,职业,品阶,HP,MaxHP,Moral,MaxMoral,操作角色ID,技能列表,Buff列表,坐骑ID,坐骑属性,援助列表,援助属性)
CreateHeroUnit = 5			#创建英雄【跑步入场】(操作码,key,位置,角色ID,英雄类型,等级,HP,最大HP)
CreateMonsterUnit = 6		#创建怪物【跑步入场】(操作码,key,位置,怪物id,等级,HP,MaxHP)
Leave = 7					#离场(操作码,离场者key)
End = 8						#结束战斗【fight】(操作码,战斗结果1;0;-1, 统计字典)
Round = 9					#回合数【fight】(操作码, 回合数)
UserSkill = 10				#使用技能【fight】(操作码,使用者key,技能id,before_list,targets,after_list)
DoTarget = 11				#对目标释放【target】(操作码,目标key)
HasBroken = 12				#破击【target】(操作码,被破击者key)
HasCrit = 13				#暴击【target】(操作码,被暴击者key)
HasParry = 14				#格挡【target】(操作码,格挡者key)
CreateBuff = 15				#创建Buff(操作码,buff_key,获得者key,buff_id,buff生命值)
DeleteBuff = 16				#消失Buff(操作码,buff_key)
ChangeHP = 17				#改变血量(操作码,改变者key,改变量,飘数字)
DoHurt = 18					#伤害导致改变血量(操作码,改变者key,改变量,飘数字)
DoTreat = 19				#治疗导致改变血量(操作码,改变者key,改变量,飘数字)
ChangeMaxHP = 20			#改变最大血量(操作码,改变者key,改变量)
ChangeMoral = 21			#改变士气(操作码,改变者key,改变量)
ChangeMaxMoral = 22			#改变最大士气(操作码,改变者key,改变量)
SelectSkill = 23			#选择一个技能【fight】(操作码,控制角色ID)
ReduceHurt = 24				#显示吸收伤害(操作码,吸收者key,吸收量)
ChangeAttack = 25			#改变攻击(操作码,改变者key,改变量)
BuyLife = 26				#战斗中买活【fight】(操作码,控制角色ID,已经购买次数)
MonsterWave = 27			#怪物波数【fight】(操作码,已经创建怪物波数，还剩余的怪物波数)
FightRound = 29				#战斗回合数
ShieldNumber = 30			#盾的生命(操作码,key,数字)
FightMsg = 31				#战斗消息(操作码,参数1,参数2,字符串)
HeadPortrait = 32			#头像(操作码, 镜像, {role_id:[role_name, sex, career, grade, is_dead, fight_index]})
ChangeDefence = 33			#改变防御(操作码,改变者key,改变量)
StarGirlUnit = 34			#星灵【直接出来】(操作码,key,位置,等级,HP,MaxHP,星灵ID,星灵品阶,Moral,角色ID,星灵星级,控制角色ID)
CreateStarGirlUnit = 35		#创建星灵【跑步入场】(操作码,key,位置,等级,HP,MaxHP,星灵ID,星灵品阶,Moral,角色ID,星灵星级,控制角色ID)
WaitTimePoint = 36			#需要等待到的时间(操作码,UnixTime)
SetSkillRound = 37			#设置技能CD(操作码,改变者key,技能ID,设置上次释放技能的回合)
ClearSkillCD = 38			#清理技能CD(操作码,改变者key,技能ID)
